name: medaical_schedulair
description: A Windows desktop scheduling app for doctors and nurses built with Flutter.
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.5
  postgres: ^3.5.6
  record: ^6.0.0
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/brand/medaical_wordmark.svg
